### PR TITLE
Change Treeprocessor to TreeProcessor and create an alias for backwar…

### LINKED ISSUE #815: alias TreeProcessor to Treeprocessor
In the interest of consistency with `BlockProcessor` and most other `*Processor`. I suggest to provide an alias `TreeProcessor` to the class `Treeprocessor`.

This would reduce the friction for extension writers. At least a bit.

### PR DESCRIPTION
**Pull request by venthur**
…ds compatibility.

Closes: #815

### CODE REVIEW

**Comment by venthur** [comment]
Not sure which of the other classes matching `*TreeProcessor` need an alias too, just let me know, and I'll update accordingly.

**Comment by waylan** [comment]
I'm inclined to not merge this as the current capitalization matches the other classes (preprocessor, postprocessor, etc.). Anyone else have any thoughts?

**Comment by facelessuser** [comment]
FYI, BlockProcessor is an outlier: https://github.com/Python-Markdown/markdown/blob/master/markdown/blockprocessors.py#L59. I'm not sure which way you'd like to normalize class names 🤷🏻.

**Comment by waylan** [comment]
So it would appear that for the least amount of change we would change `BlockProcessor => Blockprocessor`, which would result in a consist style.

If we went the other way, we would need to change everything except `BlockProcessor`. Although, I can see an argument for not camel casing `Preprocessor` as that would be a single work in normal English prose. I suspect that is where the current style of not camel casing any of them case from. `BlockProcessor` was certainly a later addition and perhaps we forgot about that earlier style choice.

**Comment by venthur** [comment]
I'm fine either way, I've now also created https://github.com/Python-Markdown/markdown/pull/1290 that changes spelling for the `BlockProcessor` to `Blockprocessor`

**Pull request closed without merging**
