### PR TITLE
Add .travis.yml for continuous integration

### PR DESCRIPTION
**Pull request by mitya57**
I have set up an account for myself, and it works: https://travis-ci.org/mitya57/Python-Markdown. Maybe you'll want to do the same (Travis is really a cool thing, and it can even check all incoming pull requests).

### CODE REVIEW

**Comment by waylan** [comment]
@mitya57 thanks for the extra push to finally do this. As you can see I implemented it a little different for the reasons stated in my commit message (also had to fix it in 94808ec37). However, I'm glad I did, as there is a [failing test](https://travis-ci.org/waylan/Python-Markdown/builds/21469913) only when running the extra tests that require tidylib (I have no idea what is causing the bug and find it curious that is doesn't exist on Python 3.3).

**Comment by mitya57** [comment]
Nice, I tried to `pip install pytidylib`, but that didn't work without libtydy itself, and I didn't realize you can `apt-get install` stuff.

**Comment by mitya57** [comment]
Re the failing test, I don't see why &ldquo;Headers below should appear exactly as they are typed (no backslash added or removed)&rdquo;. I.e., if I put a single backslash, I want to escape the next character, and if I want a real backslash, I would put a double backslash.

Also, can you reproduce it locally (and if yes, on what OS)? I can't.

**Comment by waylan** [comment]
@mitya57 I have responded to this in the discussion on issue #264. Please take any further discussion there. Thanks.

**Pull request closed without merging**
