### PR TITLE
Release Notes and a fix for Smarty

### PR DESCRIPTION
**Pull request by mitya57**
I have fixed a bug in Smarty extension (and removed a bunch of mostly useless code), and updated the release notes, as well as making some other documentation fixes.

### CODE REVIEW

**Comment by mitya57** [comment]
By the way, have you considered setting up Travis integration for Python-Markdown? I think it would be useful to see if changes break/fix tests.

**Comment by waylan** [comment]
@mitya57 thanks for your work on this. I really appreciate it. I had looked into Travis back when I adopted tox, but didn't see any additional value at the time. Perhaps I need to reconsider. I'm getting a lot more user contributed code than I used to (mostly because I don't have the time to do it myself anymore).

**Comment by mitya57** [comment]
Is anything else blocking the release (where I can help)?

**Comment by mitya57** [comment]
@waylan Thanks for the release!

**Pull request merged**
