### PR TITLE
Completes pull #1043 which fixes #1040

### LINKED ISSUE #1040: markdown.extensions.md_in_html fails with TypeError: expected string or bytes-like object
I'm running into an issue with "simple" Markdown + HTML examples crashing with a `TypeError`. For example, the following throws a `TypeError: expected string or bytes-like object` exception:

```python
markdown.markdown(
    'Hello\n<div markdown="1"></div>', 
    extensions=["markdown.extensions.md_in_html"],
)
```

Versions: `Markdown==3.3.1`, CPython 3.8.6

I haven't had time yet to investigate this further, but I wanted to get an issue opened with some failing test cases in case others are running into this as well. I suspect this has something to do with the raw HTML parser rewrite in #803.

## Steps to reproduce:

Save the following as `mderror.py`:

```python
import traceback
import markdown


def try_render(text):
    print(f"\n\n---- Rendering: {text!r}")
    try:
        html = markdown.markdown(
            text, extensions=["markdown.extensions.md_in_html"],
        )
        print(f"---- PASS: {html!r}")
    except Exception as e:
        print("---- FAILED")
        traceback.print_exc()


try_render('Hello<div markdown="1"></div>')  # Error
try_render('Hello\n<div markdown="1"></div>')  # Error
try_render('Hello\n\n<div markdown="1"></div>')  # Okay
```

Result:

```console
$ python mderror.py


---- Rendering: 'Hello<div markdown="1"></div>'
<Element 'div' at 0x110758310>
---- FAILED
Traceback (most recent call last):
  File "mderror.py", line 8, in try_render
    html = markdown.markdown(
  File "PROJECT_ROOT/venv/lib/python3.8/site-packages/markdown/core.py", line 386, in markdown
    return md.convert(text)
  File "PROJECT_ROOT/venv/lib/python3.8/site-packages/markdown/core.py", line 290, in convert
    output = pp.run(output)
  File "PROJECT_ROOT/venv/lib/python3.8/site-packages/markdown/postprocessors.py", line 73, in run
    if self.isblocklevel(html):
  File "PROJECT_ROOT/venv/lib/python3.8/site-packages/markdown/postprocessors.py", line 94, in isblocklevel
    m = re.match(r"^\<\/?([^ >]+)", html)
  File "/Users/dbader/.pyenv/versions/3.8.6/lib/python3.8/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object


---- Rendering: 'Hello\n<div markdown="1"></div>'
<Element 'div' at 0x110758900>
---- FAILED
Traceback (most recent call last):
  File "mderror.py", line 8, in try_render
    html = markdown.markdown(
  File "PROJECT_ROOT/venv/lib/python3.8/site-packages/markdown/core.py", line 386, in markdown
    return md.convert(text)
  File "PROJECT_ROOT/venv/lib/python3.8/site-packages/markdown/core.py", line 290, in convert
    output = pp.run(output)
  File "PROJECT_ROOT/venv/lib/python3.8/site-packages/markdown/postprocessors.py", line 73, in run
    if self.isblocklevel(html):
  File "PROJECT_ROOT/venv/lib/python3.8/site-packages/markdown/postprocessors.py", line 94, in isblocklevel
    m = re.match(r"^\<\/?([^ >]+)", html)
  File "/Users/dbader/.pyenv/versions/3.8.6/lib/python3.8/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object


---- Rendering: 'Hello\n\n<div markdown="1"></div>'

---- PASS: '<p>Hello</p>\n<div></div>'
```

### PR DESCRIPTION
**Pull request by facelessuser**
Completes the tests in #1043 which fixes #1040

### CODE REVIEW

**Comment by waylan** [comment]
Looks good. There is one more test case we should probably include:

```
<div markdown="1">*foo*</div><div markdown="1">*bar*</div>
```

Specifically a ` markdown="1"` element in the tail of a ` markdown="1"` element. That should render as:

```
<div><p><em>foo</em></p></div>
<div><p><em>bar</em></p></div>
```

I suspect that might cover the scenario there is no test coverage for in your patch.

**Comment by facelessuser** [comment]
Yeah, I'll add that test. I just wanted to make sure the direction was fine first.

**Comment by facelessuser** [comment]
I will most likely address https://github.com/Python-Markdown/markdown/issues/1045 here as well. I'll just make this the "fix HTML parsing" pull.

**Comment by waylan** [comment]
Your approach for handling tails is a little different than mine. In the core parser, I track the tail by setting `self.intail` at the end of a block...

https://github.com/Python-Markdown/markdown/blob/607a091918004c4ca10fb621e53a09a00b8d299b/markdown/htmlparser.py#L150-L155

... and then checking the status of `self.intail` at the start of the next one. 

https://github.com/Python-Markdown/markdown/blob/607a091918004c4ca10fb621e53a09a00b8d299b/markdown/htmlparser.py#L123-L126

The status gets reset on the first newline.

https://github.com/Python-Markdown/markdown/blob/607a091918004c4ca10fb621e53a09a00b8d299b/markdown/htmlparser.py#L166-L167

However, you are simply adding a blank line after the end of the block, which is a simpler solution. I don't recall why I didn't use that solution myself. I might not have considered it, or perhaps it was mucking up some edge cases. In any event, in the md_in_html extension I'm less concerned with altering insignificant whitespace than in the default behavior.

One thing I do wonder about is what if the blank lines you are checking for also contain whitespace. For example, you check for `'\n\n'`, but what if instead the document contains `'\n    \n   '`? Maybe if you use `blank_line_re` as we do in `markdown.htmlparser` (see L150 above), that will address that concern.

**Comment by waylan** [comment]
> I will most likely address #1045 here as well. I'll just make this the "fix HTML parsing" pull.

Fine by me. Regarding that issue. I believe the problem is that I never really fully tested a mix of `markdown="1"` and regular raw HTML (it was either all one or all the other). If you have the time to go through the extension's tests, please feel free to extend them to fully test the interaction between the two.

**Comment by facelessuser** [comment]
I'm going to have to work things out on `md_in_html`

We aren't tracking `inraw` properly, but when we do, and a block element with `markdown="1"` is being processed, we have trouble getting the children in order if they have mixed content.

We seem to store raw HTML data in separate structures as other data. I've got some tricky things to work through.

**Comment by facelessuser** [comment]
We are going to probably need to refactor `treebuilder` logic along with how we store all the HTML data in `md_in_html`.

The base class doesn't use `treebuilder`, but `md_in_html` does. When we weren't updating `inraw` correctly, everything went to `treebuilder`, but that caused escaping of raw HTML in some cases. But when we update `inraw` correctly, now some data gets stored in `treebuilder` and some data doesn't, and they get synced up all wrong in the parent element.

So fairly good refactor is in order to handle the complexity of this nested content. We may have to override more of the base class in `md_in_html` than we originally wanted, not sure yet.

This definitely won't be as quick a fix as I hoped.

**Comment by waylan** [comment]
The order of things in `MarkdownInHtmlProcessor(BlockProcessor)` is very important so as not to reorder elements. In addition to the many comments documenting why the specific order is used, notice a few calls to `children.reverse()`. For example here:

https://github.com/Python-Markdown/markdown/blob/607a091918004c4ca10fb621e53a09a00b8d299b/markdown/extensions/md_in_html.py#L230-L232

However, it sounds like you are suggesting that some elements are being reordered before we ever get that far. Not sure how that is happening.

**Comment by facelessuser** [comment]
It is only happening when I try to fix `md_in_html`'s issue with #1045. The HTML content is being escaped because it isn't recognized as "raw" HTML. When I properly assign `inraw` the correct value (which doesn't happen in `md_in_html` it fixes the escape issue, but then reorders things incorrectly.

We keep processing HTML under a block element with `markdown` attribute, but we only have 1 treebuilder. Maybe I'm making it more complicated than it is.

**Comment by facelessuser** [comment]
Okay, I get what treebuilder does now, we were processing start and end tags with `treebuilder.data()` when we should have used `treebuilder.start()` or `treebuilder.end()`. I got the #1045 case fixed.

I slightly altered the case because I wanted to make sure Markdown parsed under the `markdown="1"` element.

```py
import markdown
md = markdown.Markdown(extensions=["markdown.extensions.md_in_html"])
test = """
<div markdown="1">
**test**
<div>
**test**
<img src=""/>
<code>Test</code>
<span>**test**</span>
<p>Test 2</p>
</div>
</div>
"""
print(md.convert(test))
```

Results:

```
<div>
<p><strong>test</strong></p>
<div>
**test**
<img src=""/>
<code>Test</code>
<span>**test**</span>
<p>Test 2</p>
</div>
</div>
```

Unfortunately, it broke other cases 🤦 .

**Comment by facelessuser** [comment]
I have a working fix now. I'm not convinced the `md_in_html` parser is quite operating as intended, or maybe not quite how I expected compared to the base parser, but I've isolated some fixes that work without breaking everything else.

I'll still need more coverage cases, and I'd like to run some checks on some more corner cases, but this is a good start I think.

**Comment by facelessuser** [comment]
Coverage is now being met.

Before merging, I'd like to do some more investigation. I've flagged this pull as a "work in progress" until I've had a chance to gain more confidence in this area. I think I'm quickly coming up to speed on how all the inner workings come together in the new parser.

**Comment by waylan** [comment]
I finally had a chance to look at this. Looking good. 👍

**Comment by facelessuser** [comment]
@waylan So, I added a whitespace case that mixes newlines with spaces. I can't see a need (at least in `md_in_html`) to add the regex for newlines. Am I missing some kind of newline case? I'm just thinking that due to the way things get processed, this appears to be a non-issue.

**Comment by waylan** [comment]
That test seems fine to me. If that’s passing as-is, then that should be fine.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by facelessuser** [comment]
Cool. I'll try and wrap up my testing by the end of the weekend. If I'm not done by then. I'm probably done anyways 🙃. From what I can tell, the big holes seemed filled now.

**Comment by facelessuser** [comment]
I'm going to call this done for now. I'm generally feeling good about the changes. They solve the current issues and don't break existing tests. I can't think of specific cases that I'm not covering, but if more are found, I gladly take another look.

Probably won't have much more time to look at this over the weekend, and I don't want to hold up a fix.

**Pull request merged**
