### PR TITLE
CodeHilite: allow custom lexers

### PR DESCRIPTION
**Pull request by AshleyYakeley**
This allows custom Pygments lexers to be specified in the configuration.

### CODE REVIEW

**Comment by facelessuser** [comment]
I'm confused. You can already use custom lexers by creating a pygments lexer according to their documentation. It should use the appropriate entry points, and if it does, it will be recognized. I'm not sure this is needed. Can you clarify why you think something like this is needed?

**Comment by AshleyYakeley** [comment]
I am using MkDocs, which uses Python-Markdown. I can't figure out any other way to get it to load custom Pygments lexer files.

**Comment by facelessuser** [comment]
I've done them before, you have to specify their entry points and then install them. Here  I have two lexers that I setup with entry points: https://github.com/facelessuser/pymdown-lexers/blob/master/setup.py#L7.

I install my custom lexer package, and then I specify fences with my custom lexer name.

**Comment by AshleyYakeley** [comment]
Oh this makes a lot more sense than fiddling with the CodeHilite code.

Thanks for pointing this out...

**Comment by facelessuser** [comment]
Not a problem. The idea is to work within the design constraints of Pygments instead of reimplementing Pygments plugin access here.

You can use that repo I pointed to as a reference. You should be able to use the basic framework of it to get your own working. You can use a similar approach to do custom Pygments styles as well.

**Pull request closed without merging**
