### PR TITLE
Made package do specific imports from xml.etree.ElementTree to prevent collision with defusedxml

### PR DESCRIPTION
**Pull request by OrBin**
This comes in order to fix an error I experience when using both `markdown` and `defusedxml`:
```
TypeError: insert() argument 2 must be xml.etree.ElementTree.Element, not Element
```
My solution is based on [this comment](https://github.com/tiran/defusedxml/issues/43#issuecomment-562995041) on the issue in `defusedxml`.

### CODE REVIEW

**Comment by OrBin** [comment]
Actually it looks like it still doesn't fix my issue, I guess this is due to the fact that utils.py imports the whole `xml.etree.ElementTree` anyway. Do I have another way to keep this functioning without importing the whole module?

**Comment by OrBin** [comment]
Turns out that the fix is probably needed in `pymdown-extensions`, not in `markdown`, so I'm closing this PR.

**Comment by waylan** [comment]
Please see #950. This is an issue that needs to be fixed by defusedxml. Even if your "fix" worked, would we always maintain the same behavior with future changes? We can't guarantee that. And its not reasonable for us to test against some random third party lib which we don't use. After all, we are using common Python APIs that always work everywhere else. Defusedxml is the only thing that is broken here, so that is where the fix needs to happen.

**Comment by facelessuser** [comment]
I am the author of pymdown-extensions, and I will not support such a hack either. Effort should be put into getting defusedxml to fix this on their end instead.

**Pull request closed without merging**
