### PR TITLE
Add `set_css_classes` configuration option to the table extension

### PR DESCRIPTION
**Pull request by mikev-db**
A new boolean option `set_css_classes` adds css classes to the table generation. These classes include row and columns counts and parity and will allow for more granular table styling.

### CODE REVIEW

**Comment by waylan** [comment]
Interesting suggestion. However, I'm curious why it has taken so many years for anyone to ask for this. Makes me wonder if it is necessary. Is there a way to accomplish what you want without these classes? If so they are redundant and unnecessary.

**Comment by facelessuser** [comment]
Using things like `:nth-child()` for styling is really all that is needed. I guess adding classes could make it "easier", but I'd argue not necessary.

**Comment by mikev-db** [comment]
@facelessuser I am using this in email templates, and gmail, outlook, etc do not support `:nth-child()`. I could not find any other way to accomplish this.  Thanks!

**Comment by waylan** [comment]
If you search through past feature requests you will see that I am generally resistant to adding features to the tables extension. The extension provides the most basic table support. For anything more than that, a third party extension should be used (of which there are many). As this is not necessary in the common case, I am not inclined to add it.

**Comment by mikev-db** [comment]
Alright. I'll hunt around for third-party extensions that might fit the bill. (Prefer not to maintain this as I'll be handing it off at some point). If either of you happen to know of one or a way around this issue, happy to hear it. I tried all the css I could think of but couldn't really make it happen.  Thanks @waylan, @facelessuser.

**Pull request closed without merging**
