### PR TITLE
Suggested fix for Issue #52 - supporting markdown="1" in nested blocks

### PR DESCRIPTION
**Pull request by christopherjwhite**
Attempt to track the depth level for the tag that was marked as markdown="1" and only perform markdown when the matching tag according to depth is found.

### CODE REVIEW

**Comment by waylan** [comment]
@christopherjwhite looks interesting. Do you have any tests for that?

**Comment by christopherjwhite** [comment]
I have a small test file I was using -- let me see if I can get that integrated into the test framework.

**Comment by christopherjwhite** [comment]
Ok, found the raw-html.txt test and using that.  Found an issue that will take a bit more time, let me poke at it some more...

**Comment by christopherjwhite** [comment]
Going to close this for now.  The entire html block parsing needs more work.  Even without any blocks with markdown="1" I found some problems. 

The following example illustrates the issue:

```
<div>

Nested inside a _plain_ div.

<div>

_foo_

</div>

_bar_

</div>
```

The closing div after _foo_ but before _bar_ is detected as the end of the block that started at the top, which does not take nesting into account.

I have some ideas on how to better clean this up, but will take more testing.

**Pull request closed without merging**
