### PR TITLE
add: use stacklevel=2 with warning

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/encode/django-rest-framework/issues/6317

### CODE REVIEW

**Comment by mitya57** [comment]
This may be useful in other places where we issue warnings, too.

**Comment by blueyed** [comment]
Some places where using it already, but looking again it is missing here: https://github.com/blueyed/markdown/blob/1052b333472a9702badf26e08841e030ed0d4b18/markdown/util.py#L421-L451

Not sure about dunder-methods and warnings though, so would need more investigation.

**Comment by waylan** [comment]
> looking again it is missing here: https://github.com/blueyed/markdown/blob/1052b333472a9702badf26e08841e030ed0d4b18/markdown/util.py#L421-L451

As those are all related to the same feature, they should all behave the same. Could you make the same change there as well?

**Comment by blueyed** [comment]
Updated.
Please test/verfify.

**Pull request merged**
