### PR TITLE
Just a workflow test

### PR DESCRIPTION
**Pull request by facelessuser**

### CODE REVIEW

**Comment by facelessuser** [comment]
Interesting, when done on my fork it works: https://github.com/facelessuser/markdown/pull/1

But when I do it here, it does not.

**Comment by facelessuser** [comment]
Seems like an organization issue...maybe we are missing something?

**Comment by facelessuser** [comment]
Maybe this is relevant? https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/disabling-or-limiting-github-actions-for-your-organization

**Comment by waylan** [comment]
> Maybe this is relevant? https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/disabling-or-limiting-github-actions-for-your-organization

Yeah I checked that and it was already enabled. Although, I clicked `save` anyway and got a message that actions are now enabled for all repos. I don't know if that message always displays when you click save or if it actually indicates a change.

As another data point, under the projects actions tab I clicked the `add runner` button and got a message that actions were not set up. It indicated that I needed to create a workflow file. I get the sense that it won't run until there is at least a workflow file in the master branch. It's just weird that we can't test it before committing to master. 

> Interesting, when done on my fork it works: facelessuser#1

That is weird because the documentation clearly states that actions are disabled for forks unless explicitly enabled by the user. Sorry, I forget where I read that.

**Comment by facelessuser** [comment]
> That is weird because the documentation clearly states that actions are disabled for forks unless explicitly enabled by the user. Sorry, I forget where I read that.

Since it was implemented on a fork and requested to merge to that fork, it is probably fine. But I guess it then makes sense that it won't work if I try to merge it back to yours. If you create a branch under the org, I bet it would work, but you are merging from your waylan account.

**Comment by facelessuser** [comment]
I suggest create the branch under the org instead of under waylan and develop it there. Once it is on the main branch, I bet it will run for forks.

**Comment by facelessuser** [comment]
Sounds like you got it working, so closing this.

**Pull request closed without merging**
