### PR TITLE
modernized syntax allowed for py37+

### PR DESCRIPTION
**Pull request by venthur**
This pr modernizes the syntax for things that are allowed for pyhton3.7+. It is mostly

* ''.format -> f''
* set() -> {}
* removal of explicit utf8 encoding of files

this is related to #760

### CODE REVIEW

**Comment by waylan** [comment]
Please note that the [Contributing Guide][1] states the following:

> Legacy code which does not follow the guidelines should only be updated if and when other changes (bug fix, feature addition, etc.) are being made to that section of code.

That said, `.format -> f'` could be classified as a performance improvement, especially if we were provided some numbers to back it up. However, that should be a separate PR by itself. And removal of explicit utf8 encoding of files could be considered code cleanup I suppose (again as a separate PR. However, `set() -> {}` is clearly a style thing and the sort of change our Contributing Guide discourages.

[1]: https://python-markdown.github.io/contributing/#code-style-guide

**Comment by venthur** [comment]
Alright, I thought it might help to cleanup the code a bit, but feel free to reject the PR if it is not needed.

**Comment by waylan** [comment]
As I said, if you want to do the work to show that the `.format -> f'` change provides us with a clear performance improvement, then we would be happy to accept the work.

However, I don't actually see any changes which remove explicit utf8 encoding of files. So if you want to reclassify the PR to be about the first issue you can. Just remove the set changes.

**Comment by venthur** [comment]
> As I said, if you want to do the work to show that the .format -> f' change provides us with a clear performance improvement, then we would be happy to accept the work.

No not really, actually. If you don't like the proposal you can just go ahead and close it. No hard feelings.

> However, I don't actually see any changes which remove explicit utf8 encoding of files. So if you want to reclassify the PR to be about the first issue you can. Just remove the set changes.

It is at the very bottom of the diff:

https://github.com/Python-Markdown/markdown/pull/1304/files#diff-57787454b56d61377fe6ec8e971df1e1e1ec9d6f1f0dd4a13209bf5bfb55633bL1

The idea of the PR was to make the code more readable, I was not aware of that rather strict guideline not to touch code unless it fixes something else. Sorry for the noise.

**Comment by akx** [comment]
Seems to be a revisit of my #1215, fwiw.

**Comment by waylan** [comment]
I'm closing this. If an update to provided which addresses the concerns raised, we can reopen.

**Pull request closed without merging**
